name: example
description: Interactively evaluate FHIRPath expressions
publish_to: "none"

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fhir: ^0.5.0-12
  fhir_path:
    path: ../../fhir_path
  google_fonts: ^2.2.0
  url_launcher: ^6.0.17
  yaml_writer: ^1.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: SourceCodePro
      fonts:
        - asset: google_fonts/SourceCodePro-Regular.ttf
