name: example
description: Interactively evaluate FHIRPath expressions
publish_to: "none"

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fhir: 
    path: ../../fhir
  fhir_path:
    path: ../../fhir_path
  google_fonts: ^2.3.2
  url_launcher: ^6.1.0
  yaml_writer: ^1.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: SourceCodePro
      fonts:
        - asset: google_fonts/SourceCodePro-Regular.ttf
