name: fhir_bulk
description: A Dart/Flutter package for working with FHIR bulk data. Also includes ability to archive.
version: 0.4.2
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_bulk

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  archive: ^3.1.2
  fhir: ^0.4.3
  freezed_annotation: ^0.14.1
  http: ^0.13.1
  mime: ^1.0.0
  universal_io: ^2.0.4



dev_dependencies:
  build_runner: ^1.12.2
  freezed: ^0.14.1
  lint: ^1.5.3
  test: ^1.16.8