name: fhir_bulk
description: A Dart/Flutter package for authorization & authentication, includes SMART on FHIR and Google sign-in
version: 0.3.0-nullsafety.2
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_bulk

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  archive: ^3.1.2
  dartz: ^0.10.0-nullsafety.1
  fhir: ^0.4.0
  freezed_annotation: ^0.14.1
  http: ^0.13.0
  mime: ^1.0.0
  universal_io: ^2.0.0-nullsafety.2



dev_dependencies:
  build_runner: ^1.11.5
  freezed: ^0.14.1
  lint: ^1.5.3
  test: ^1.16.4