name: fhir_bulk
description: A Dart/Flutter package for authorization & authentication, includes SMART on FHIR and Google sign-in
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dartz: ^0.9.2
  fhir: ^0.2.3

dev_dependencies:
  lint: ^1.2.0
  test: ^1.15.7

assets:
  - assets/