name: fhir_bulk
description: A Dart/Flutter package for authorization & authentication, includes SMART on FHIR and Google sign-in
version: 0.2.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  archive: ^2.0.13
  dartz: ^0.9.2
  fhir: ^0.2.4
  freezed_annotation: ^0.12.0
  http: ^0.12.2
  mime: ^0.9.7

dev_dependencies:
  build_runner: ^1.11.0
  freezed: ^0.12.7
  lint: ^1.2.0
  test: ^1.15.7