name: web_auth_demo
description: A Dart/Flutter package for authorization & authentication, includes SMART on FHIR and Google sign-in
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  fhir_auth:
    path: ../../fhir_auth
  fhir: ^0.4.6
  flutter:
    sdk: flutter