name: fhir
description: FHIR library of versions R4, STU3, DSTU2, and R5 (draft) for Dart & Flutter.
version: 0.0.2
homepage: https://github.com/Dokotela/fhir/tree/main
repository: https://github.com/Dokotela/fhir

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1
  dartz: ^0.9.1
  string_validator: ^0.1.4
  freezed_annotation: ^0.11.0

dev_dependencies:
  json_serializable: ^3.3.0
  build_runner: ^1.8.1
  freezed: ^0.11.0