name: fhir
description: FHIR R4, STU3 and DSTU2 for Dart & Flutter.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1
  http: ^0.12.0+4
  dartz: ^0.8.9
  string_validator: ^0.1.4
  freezed: ^0.10.6

dev_dependencies:
  json_serializable: ^3.3.0
  build_runner: ^1.8.1