name: fhir_us_core
description: FHIR library for the use of profiles. Will need auth, bulk, and restful requests from those libraries.
version: 0.9.0-1
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_us_core

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # fhir: ^0.8.0
  fhir:
    path: ../fhir
  # fhir_at_rest: ^0.8.0
  fhir_at_rest:
    path: ../fhir_at_rest
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3
  json_serializable: ^6.2.0
  lint: ^1.8.2
  test: ^1.21.3
