name: fhir_auth
description: A Dart/Flutter package for authorization & authentication, includes SMART on FHIR and Google sign-in
version: 0.1.0
homepage: https://github.com/fhir-fli/fhir_auth

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.12.0
  flutter_appauth: ^0.9.2+6
  fhir: ^0.1.5
  google_sign_in: ^4.5.6
  dartz: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.12.6
  build_runner: ^1.10.11
  lint: ^1.2.0
  test: ^1.15.7