name: fhir_auth
description: A Dart/Flutter package for authorization & authentication, includes SMART on FHIR and Google sign-in
version: 0.5.0-6
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_auth

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  fhir: ^0.5.0-9
  flutter:
    sdk: flutter
  freezed_annotation: ^1.0.0
  google_sign_in: ^5.2.1
  http: ^0.13.4
  oauth2: ^2.0.0
  oauth2_client: ^2.3.0
  universal_html: ^2.0.8

dev_dependencies:
  build_runner: ^2.1.5
  freezed: ^1.0.0
  lint: ^1.7.2
  pedantic: ^1.11.1
  test: ^1.19.4

