name: fhir_auth
description: A Dart/Flutter package for authorization & authentication, includes SMART on FHIR and Google sign-in
version: 0.1.0
homepage: https://github.com/fhir-fli/fhir_auth

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.2
  fhir: ^0.2.3
  flutter_appauth: ^0.9.2
  flutter_secure_storage: ^3.3.5
  freezed_annotation: ^0.12.0
  google_sign_in: ^4.5.9
  oauth2: ^1.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.0
  freezed: ^0.12.7
  lint: ^1.2.0
  test: ^1.15.7

assets:
  - assets/