name: fhir_path

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  antlr4: ^4.9.2
  collection: ^1.15.0
  fhir: 
    path: ../fhir
  equatable: ^2.0.3
  js: ^0.6.3
  petitparser: ^4.2.0

dev_dependencies:
  test: ^1.9.0
