name: mobileauthdemo

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  fhir: ^0.6.2
  fhir_auth:
    path: ../../fhir_auth
  flutter:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/
