name: mobileauthdemo

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  fhir: ^0.7.0
  fhir_auth:
    path: ../../fhir_auth
  flutter:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  uses-material-design: true
  assets:
  - assets/
