name: mobileauthdemo

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  fhir: ^0.5.0-9
  fhir_auth:
    path: ../../fhir_auth
  flutter:
    sdk: flutter
  google_sign_in: ^5.2.1
  oauth2_client: ^2.3.0
  url_launcher: ^6.0.16

  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true