name: fhir_auth_example

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  fhir: ^0.1.5
  fhir_at_rest: ^0.1.0
  fhir_auth:
    path: ../../fhir_auth

dev_dependencies:
  flutter_test:
    sdk: flutter