name: fhir
description: FHIR library of versions R4, STU3, DSTU2, and R5 (draft) for Dart & Flutter.
version: 0.4.3
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  json_annotation: ^4.0.1
  freezed_annotation: ^0.14.1
  yaml: ^3.1.0
  fhir_yaml: ^0.4.0

dev_dependencies:
  json_serializable: ^4.1.0
  build_runner: ^1.12.2
  freezed: ^0.14.1
  test: ^1.16.8
