name: fhir
description: FHIR library of versions R4, STU3, DSTU2, and R5 (draft) for Dart & Flutter.
version: 0.4.7
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  fhir_yaml: ^0.4.0
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1
  uuid: ^3.0.4
  yaml: ^3.1.0

dev_dependencies:
  json_serializable: ^4.1.3
  build_runner: ^2.0.4
  freezed: ^0.14.2
  test: ^1.17.5
