name: fhir
description: FHIR library of versions R4, STU3, DSTU2, and R5 (draft) for Dart & Flutter.
version: 0.5.0-3
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  fhir_yaml: ^0.5.1
  freezed_annotation: ^0.14.3
  json_annotation: ^4.1.0
  uuid: ^3.0.4
  yaml: ^3.1.0

dev_dependencies:
  json_serializable: ^5.0.2
  build_runner: ^2.1.2
  freezed: ^0.14.5
  test: ^1.17.12
