name: fhir_uscore
description: FHIR library profile for UsCore based on R4.
version: 0.3.0-nullsafety.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  json_annotation: ^4.0.0
  freezed_annotation: ^0.13.0-nullsafety.0
  yaml: ^3.0.0
  fhir_yaml: ^0.3.0-nullsafety.0 

dev_dependencies:
  json_serializable: ^4.0.0
  build_runner: ^1.11.1
  freezed: ^0.13.0-nullsafety.2 
  test: ^1.16.2
