name: fhir_uscore
description: FHIR library for the use of profiles. Will need auth, bulk, and restful requests from those libraries.
version: 0.9.1
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_uscore

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # fhir: ^0.9.0
  fhir:
    path: ../fhir
  # fhir_at_rest: ^0.9.0
  fhir_at_rest:
    path: ../fhir_at_rest
  freezed_annotation: ^2.1.0
  http: ^0.13.5
  json_annotation: ^4.7.0

dev_dependencies:
  import_sorter: ^4.6.0
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.0
  lint: ^1.10.0
  test: ^1.21.6
