name: fhir_uscore
description: FHIR library profile for UsCore based on R4.
version: 0.3.0-nullsafety.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.0
  freezed_annotation: ^0.13.0-nullsafety.0
  yaml: ^3.0.0
  fhir_yaml: ^0.3.0-nullsafety.0 
  dartz: ^0.10.0-nullsafety.1
  http: ^0.13.0
  flutter_appauth: ^1.0.0-nullsafety.0
  flutter_secure_storage: ^4.0.0
  archive: ^3.0.0
  mime: ^1.0.0

dev_dependencies:
  json_serializable: ^4.0.1
  build_runner: ^1.11.5
  freezed: ^0.13.0-nullsafety.2 
  test: ^1.16.3
  flutter_test:
    sdk: flutter