name: auth
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  fhir: ^0.4.2
  fhir_at_rest: ^0.4.0
  fhir_auth:
    path: ../../fhir_auth
  flutter:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true