name: fhir_at_rest
description: This package builds on the basic FHIR package. It allows easy
  creation of RESTful calls to a FHIR server or FHIR API.
version: 0.6.2
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_at_rest

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  fhir: ^0.6.0
  freezed_annotation: ^1.1.0
  http: ^0.13.4

dev_dependencies:
  analyzer: ^3.4.1
  build_runner: ^2.1.8
  freezed: ^1.1.1
  import_sorter: ^4.6.0
  pedantic: ^1.11.1
  test: ^1.20.2


