name: fhir_at_rest
description: This package builds on the basic FHIR package. It allows easy
  creation of RESTful calls to a FHIR server or FHIR API.
version: 0.9.1
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_at_rest

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # fhir: ^0.9.0
  fhir: 
    path: ../fhir
  freezed_annotation: ^2.1.0
  http: ^0.13.5
  json_annotation: ^4.7.0
 
dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.1
  import_sorter: ^4.6.0
  json_serializable: ^6.4.0
  test: ^1.21.6


