name: fhir_at_rest
description: This package builds on the basic FHIR package. It allows easy
  creation of RESTful calls to a FHIR server or FHIR API.
version: 0.3.0-nullsafety.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_at_rest

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:

  freezed_annotation: ^0.13.0-nullsafety.0
  fhir: 
    path: ../fhir
  http: ^0.13.0

dev_dependencies:
  build_runner: ^1.11.5
  freezed: ^0.13.0-nullsafety.2
  test: ^1.16.3

