name: fhir_at_rest
description: This package builds on the basic FHIR package. It allows easy
  creation of RESTful calls to a FHIR server or FHIR API.
version: 0.2.2
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_at_rest

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  fhir: ^0.2.2
  freezed_annotation: ^0.12.0
  http: ^0.12.2

dev_dependencies:
  build_runner: ^1.11.0
  freezed: ^0.12.7
  test: ^1.15.7
