name: fhir_db
description: A wrapper for Sembast and SQFlite to enable easy, local and secure storage of fhir resources
version: 0.3.0-nullsafety.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_db

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  crypto: ^3.0.0
  encrypt: ^4.1.0
  fhir: ^0.3.0-nullsafety.0
  flutter:
    sdk: flutter
  meta: ^1.3.0
  path: ^1.8.0
  path_provider: ^2.0.0
  sembast: ^3.0.0
  sembast_sqflite: ^2.0.0
  sqflite: ^2.0.0