name: fhir_yaml
description: Dart package to format JSON data to YAML. Supports formatting conventions of pubspec files.
version: 0.3.0-nullsafety.0
homepage: https://github.com/MayJuun/fhir/tree/main/fhir_yaml

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  test: ^1.16.4
  test_coverage: ^0.5.0
  yaml: ^3.0.0
