name: fhir_db_test

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fhir_db:
    path: ../../fhir_db
  fhir: 
    path: ../../fhir

dev_dependencies:
  dependency_validator: ^2.0.1
  test: ^1.15.7
  test_coverage: ^0.5.0